const data = {
  products: [
    {
      _id: "1",
      name: "Samsung 43 Inch Full HD Smart LED TV with Built-in Receiver, Black - UA43T5300AUXEG",
      description:
        "Samsung 43 Inch Full HD Smart LED TV with Built-in Receiver, Black - UA43T5300AUXEG",
      category: "TV",
      image: "/images/samsungtv.jpg",
      price: "90000",
      countInstock: 10,
      brand: "Samsung",
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: "2",
      name: "Samsung 43 Inch Full HD Smart LED TV with Built-in Receiver, Black - UA43T5300AUXEG",
      description:
        "Samsung 43 Inch Full HD Smart LED TV with Built-in Receiver, Black - UA43T5300AUXEG",
      category: "TV",
      image: "/images/samsungtv.jpg",
      price: "90000",
      countInstock: 10,
      brand: "Samsung",
      rating: 4.6,
      numReviews: 9,
    },
    {
      _id: "3",
      name: "Samsung 43 Inch Full HD Smart LED TV with Built-in Receiver, Black - UA43T5300AUXEG",
      description:
        "Samsung 43 Inch Full HD Smart LED TV with Built-in Receiver, Black - UA43T5300AUXEG",
      category: "TV",
      image: "/images/samsungtv.jpg",
      price: "90000",
      countInstock: 10,
      brand: "Samsung",
      rating: 3.5,
      numReviews: 8,
    },
    {
      _id: "4",
      name: "Samsung 43 Inch Full HD Smart LED TV with Built-in Receiver, Black - UA43T5300AUXEG",
      description:
        "Samsung 43 Inch Full HD Smart LED TV with Built-in Receiver, Black - UA43T5300AUXEG",
      category: "TV",
      image: "/images/samsungtv.jpg",
      price: "90000",
      countInstock: 10,
      brand: "Samsung",
      rating: 2,
      numReviews: 6,
    },
    {
      _id: "5",
      name: "Canon EOS 90D + EF-S 18-135mm f/3.5-5.6 IS USM, Black",
      description:
        "From wildlife hide to trackside Keep up with the action shooting at 10fps with Intelligent Tracking and Recognition iTR focus tracking when using the optical viewfinder and 11fps in Live View modeSee every drop of detail A 325 megapixel sensor works with a DIGIC 8 processor to deliver superb image quality even in low light with up to ISO 25600 sensitivityIntuitive DSLR design An intelligent optical viewfinder delivers a clear bright view thats comfortable to use for long periods The EOS 90D feels balanced even with long telephoto lensesAn intelligent performance A 220000 pixel RGBIR metering sensor works with the cameras iTR focusing system for superb subject tracking following faces and other objects around the frameSuperb creative video Shoot stunning 4K video using Dual Pixel CMOS AF to keep things sharp and cinematic Capture great audio and use frame rates up to 120fps for slow motion filming",
      category: "CAMERAS",
      image: "/images/canonEOSCam.jpg",
      price: "90000",
      countInstock: 10,
      brand: "Canon",
      rating: 3,
      numReviews: 12,
    },
    {
      _id: "6",
      name: "Canon EOS 90D + EF-S 18-135mm f/3.5-5.6 IS USM, Black",
      description:
        "From wildlife hide to trackside Keep up with the action shooting at 10fps with Intelligent Tracking and Recognition iTR focus tracking when using the optical viewfinder and 11fps in Live View modeSee every drop of detail A 325 megapixel sensor works with a DIGIC 8 processor to deliver superb image quality even in low light with up to ISO 25600 sensitivityIntuitive DSLR design An intelligent optical viewfinder delivers a clear bright view thats comfortable to use for long periods The EOS 90D feels balanced even with long telephoto lensesAn intelligent performance A 220000 pixel RGBIR metering sensor works with the cameras iTR focusing system for superb subject tracking following faces and other objects around the frameSuperb creative video Shoot stunning 4K video using Dual Pixel CMOS AF to keep things sharp and cinematic Capture great audio and use frame rates up to 120fps for slow motion filming",
      category: "CAMERAS",
      image: "/images/canonEOSCam.jpg",
      price: "90000",
      countInstock: 10,
      brand: "Canon",
      rating: 1,
      numReviews: 16,
    },
    {
      _id: "7",
      name: "Canon EOS 90D + EF-S 18-135mm f/3.5-5.6 IS USM, Black",
      description:
        "From wildlife hide to trackside Keep up with the action shooting at 10fps with Intelligent Tracking and Recognition iTR focus tracking when using the optical viewfinder and 11fps in Live View modeSee every drop of detail A 325 megapixel sensor works with a DIGIC 8 processor to deliver superb image quality even in low light with up to ISO 25600 sensitivityIntuitive DSLR design An intelligent optical viewfinder delivers a clear bright view thats comfortable to use for long periods The EOS 90D feels balanced even with long telephoto lensesAn intelligent performance A 220000 pixel RGBIR metering sensor works with the cameras iTR focusing system for superb subject tracking following faces and other objects around the frameSuperb creative video Shoot stunning 4K video using Dual Pixel CMOS AF to keep things sharp and cinematic Capture great audio and use frame rates up to 120fps for slow motion filming",
      category: "CAMERAS",
      image: "/images/canonEOSCam.jpg",
      price: "90000",
      countInstock: 10,
      brand: "Canon",
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: "8",
      name: "Canon EOS 90D + EF-S 18-135mm f/3.5-5.6 IS USM, Black",
      description:
        "From wildlife hide to trackside Keep up with the action shooting at 10fps with Intelligent Tracking and Recognition iTR focus tracking when using the optical viewfinder and 11fps in Live View modeSee every drop of detail A 325 megapixel sensor works with a DIGIC 8 processor to deliver superb image quality even in low light with up to ISO 25600 sensitivityIntuitive DSLR design An intelligent optical viewfinder delivers a clear bright view thats comfortable to use for long periods The EOS 90D feels balanced even with long telephoto lensesAn intelligent performance A 220000 pixel RGBIR metering sensor works with the cameras iTR focusing system for superb subject tracking following faces and other objects around the frameSuperb creative video Shoot stunning 4K video using Dual Pixel CMOS AF to keep things sharp and cinematic Capture great audio and use frame rates up to 120fps for slow motion filming",
      category: "CAMERAS",
      image: "/images/canonEOSCam.jpg",
      price: "90000",
      countInstock: 10,
      brand: "Canon",
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: "9",
      name: "Apple iPhone 13 Pro Max 256GB Blue",
      description:
        "iPhone 13 Pro Max. The biggest Pro camera system upgrade ever. Super Retina XDR display with ProMotion for a faster, more responsive feel. Lightning-fast A15 Bionic chip. Durable design and the best battery life ever in an iPhone.",
      category: "MOBILE",
      image: "/images/appleIphone13.jpg",
      price: "90000",
      countInstock: 10,
      brand: "Apple",
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: "10",
      name: "Apple iPhone 13 Pro Max 256GB Blue",
      description:
        "iPhone 13 Pro Max. The biggest Pro camera system upgrade ever. Super Retina XDR display with ProMotion for a faster, more responsive feel. Lightning-fast A15 Bionic chip. Durable design and the best battery life ever in an iPhone.",
      category: "MOBILE",
      image: "/images/appleIphone13.jpg",
      price: "90000",
      countInstock: 10,
      brand: "Apple",
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: "11",
      name: "Apple iPhone 13 Pro Max 256GB Blue",
      description:
        "iPhone 13 Pro Max. The biggest Pro camera system upgrade ever. Super Retina XDR display with ProMotion for a faster, more responsive feel. Lightning-fast A15 Bionic chip. Durable design and the best battery life ever in an iPhone.",
      category: "MOBILE",
      image: "/images/appleIphone13.jpg",
      price: "90000",
      countInstock: 10,
      brand: "Apple",
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: "12",
      name: "Apple iPhone 13 Pro Max 256GB Blue",
      description:
        "iPhone 13 Pro Max. The biggest Pro camera system upgrade ever. Super Retina XDR display with ProMotion for a faster, more responsive feel. Lightning-fast A15 Bionic chip. Durable design and the best battery life ever in an iPhone.",
      category: "MOBILE",
      image: "/images/appleIphone13.jpg",
      price: "90000",
      countInstock: 10,
      brand: "Apple",
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: "13",
      name: "lap dell 3500 vostro ram 8G hdd 1t ssd 256 vga 2G mx330 led 15.6",
      description:
        "lap dell 3500 i7 ram 8G ddr4 hdd 1t+ ssd 256 vga 2G mx 330 led 40 fhd+windos 10",
      category: "LAPTOP",
      image: "/images/lapTopDellI7.jpg",
      price: "90000",
      countInstock: 10,
      brand: "Dell",
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: "14",
      name: "lap dell 3500 vostro ram 8G hdd 1t ssd 256 vga 2G mx330 led 15.6",
      description:
        "lap dell 3500 i7 ram 8G ddr4 hdd 1t+ ssd 256 vga 2G mx 330 led 40 fhd+windos 10",
      category: "LAPTOP",
      image: "/images/lapTopDellI7.jpg",
      price: "90000",
      countInstock: 10,
      brand: "Dell",
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: "15",
      name: "lap dell 3500 vostro ram 8G hdd 1t ssd 256 vga 2G mx330 led 15.6",
      description:
        "lap dell 3500 i7 ram 8G ddr4 hdd 1t+ ssd 256 vga 2G mx 330 led 40 fhd+windos 10",
      category: "LAPTOP",
      image: "/images/lapTopDellI7.jpg",
      price: "90000",
      countInstock: 10,
      brand: "Dell",
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: "16",
      name: "lap dell 3500 vostro ram 8G hdd 1t ssd 256 vga 2G mx330 led 15.6",
      description:
        "lap dell 3500 i7 ram 8G ddr4 hdd 1t+ ssd 256 vga 2G mx 330 led 40 fhd+windos 10",
      category: "LAPTOP",
      image: "/images/lapTopDellI7.jpg",
      price: "90000",
      countInstock: 10,
      brand: "Dell",
      rating: 4.5,
      numReviews: 10,
    },
  ],

  users: [
    {
      name: "Mahmoud",
      email: "Mahmoud@gmail.com",
      password: "1234",
      isAdmin: false,
    },
  ],

  rating: [
    {
      productRating: {
        productId: "",
        numReviews: "",
        reviews: "",
      },

      userRating: {
        userId: "",
        numReviews: "",
        positiveReviews: "",
        negativeReviews: "",
      },
    },
  ],
};
export default data;
